# Generated by Django 6.1 on 2026-09-02 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='joined_date',
            field=models.DateField(),
        ),
    ]
